# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('mailboxes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_signup', 'User Signup'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('login_failed', 'Login Failed'), ('login_blocked', 'Login Blocked'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('domain_added', 'Domain Added'), ('domain_verified', 'Domain Verified'), ('domain_paused', 'Domain Paused'), ('domain_deleted', 'Domain Deleted'), ('dns_check_pass', 'DNS Check Pass'), ('dns_check_fail', 'DNS Check Fail'), ('mailbox_created', 'Mailbox Created'), ('mailbox_disabled', 'Mailbox Disabled'), ('mailbox_deleted', 'Mailbox Deleted'), ('mailbox_pw_reset', 'Mailbox Password Reset'), ('smtp_auth_ok', 'SMTP Auth Success'), ('smtp_auth_fail', 'SMTP Auth Failure'), ('smtp_msg_accepted', 'Message Accepted'), ('smtp_msg_rejected', 'Message Rejected'), ('imap_login_ok', 'IMAP Login Success'), ('imap_login_fail', 'IMAP Login Failure'), ('rule_updated', 'Rule Updated'), ('backup_completed', 'Backup Completed'), ('backup_failed', 'Backup Failed'), ('tenant_suspended', 'Tenant Suspended'), ('tenant_reactivated', 'Tenant Reactivated'), ('plan_changed', 'Plan Changed'), ('team_invite', 'Team Invite Sent'), ('role_changed', 'Role Changed'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked')], max_length=40)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_logs', to='domains.domain')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_logs', to='mailboxes.mailbox')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'logs_mail_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='logs_mail_l_tenant__0725ed_idx'), models.Index(fields=['tenant', 'event_type'], name='logs_mail_l_tenant__ddbbc0_idx')],
            },
        ),
    ]
