# Generated by Django 5.1.4 on 2026-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maillog',
            name='logs_mail_l_tenant__0725ed_idx',
        ),
        migrations.RemoveField(
            model_name='maillog',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='maillog',
            name='mailbox',
        ),
        migrations.AlterField(
            model_name='maillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='event_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='result',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='maillog',
            index=models.Index(fields=['tenant', '-created_at'], name='logs_mail_l_tenant__afd65a_idx'),
        ),
    ]
