# Generated by Django 5.1.4 on 2026-09-20 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_backfill_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(default='success', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_actions_received', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_actions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'platform_admin_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='platform_ad_created_bd456c_idx'), models.Index(fields=['action', '-created_at'], name='platform_ad_action_37b387_idx'), models.Index(fields=['tenant', '-created_at'], name='platform_ad_tenant__f10cc7_idx'), models.Index(fields=['actor', '-created_at'], name='platform_ad_actor_i_85ed9e_idx')],
            },
        ),
    ]
