# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecordCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('expected_value', models.TextField()),
                ('detected_value', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('missing', 'Missing'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_checks', to='domains.domain')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_checks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dnshealth_record_check',
                'ordering': ['domain', 'record_type'],
                'unique_together': {('domain', 'record_type', 'host')},
            },
        ),
    ]
