# Generated by Django 5.1.4 on 2026-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnshealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecordcheck',
            name='is_scored',
            field=models.BooleanField(default=True),
        ),
    ]
