# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_email', models.EmailField(max_length=254)),
                ('keep_copy', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('mail_engine_provisioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_rules', to='mailboxes.mailbox')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'forwarding_rule',
                'ordering': ['source_mailbox'],
                'unique_together': {('source_mailbox', 'destination_email')},
            },
        ),
    ]
