# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('spam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('deleted', 'Deleted'), ('sender_blocked', 'Sender Blocked')], default='held', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'quarantine_message',
                'ordering': ['-received_at'],
            },
        ),
    ]
