# Generated by Django 5.1.4 on 2026-09-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='default_storage_per_mailbox_mb',
            field=models.PositiveIntegerField(default=1024, help_text='Storage a new mailbox starts with, in MB. Must not exceed the per-mailbox maximum.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_storage_total_mb',
            field=models.PositiveIntegerField(default=10240, help_text='Total storage shared by every mailbox on a domain, in MB. Set deliberately — it is a commercial limit, not mailboxes x ceiling.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage_per_mailbox_mb',
            field=models.PositiveIntegerField(help_text='Largest a single mailbox may grow, in MB. Must not exceed the domain total.'),
        ),
    ]
