# Generated by Django 5.1.4 on 2026-09-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_storage_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_aliases',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_messages_per_day_per_tenant',
            field=models.PositiveIntegerField(default=500, help_text='Outbound messages the whole workspace may send per day.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_messages_per_hour_per_mailbox',
            field=models.PositiveIntegerField(default=50, help_text='Outbound messages one mailbox may send per hour.'),
        ),
    ]
