# Generated by Django 5.1.4 on 2026-09-20 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auth_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEmailCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Platform login'), ('password_reset', 'Platform password reset')], max_length=32)),
                ('challenge_hash', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('password_fingerprint', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_platform_email_code',
                'indexes': [models.Index(fields=['user', 'purpose'], name='accounts_pl_user_id_04789c_idx'), models.Index(fields=['expires_at'], name='accounts_pl_expires_dffb05_idx')],
            },
        ),
    ]
