# Generated by Django 5.1.4 on 2026-10-05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_backfill_approval"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomHostname",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(max_length=253)),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("hub", "MateMail Hub"),
                            ("postbox", "PostBox"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "dns_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("dns_verified_at", models.DateTimeField(blank=True, null=True)),
                ("dns_last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provisioning_status",
                    models.CharField(
                        choices=[
                            ("unprovisioned", "Unprovisioned"),
                            ("provisioning", "Provisioning"),
                            ("ready", "Ready"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("deactivating", "Deactivating"),
                            ("inactive", "Inactive"),
                        ],
                        default="unprovisioned",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not requested"),
                            ("issuing", "Issuing"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("revoked", "Revoked"),
                        ],
                        default="not_requested",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_hostnames",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenants_custom_hostname",
                "ordering": ["surface", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="customhostname",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "provisioning_status__in",
                        (
                            "unprovisioned",
                            "provisioning",
                            "ready",
                            "active",
                            "error",
                            "deactivating",
                        ),
                    )
                ),
                fields=("hostname",),
                name="uniq_live_custom_hostname",
            ),
        ),
        migrations.AddConstraint(
            model_name="customhostname",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "provisioning_status__in",
                        (
                            "unprovisioned",
                            "provisioning",
                            "ready",
                            "active",
                            "error",
                            "deactivating",
                        ),
                    )
                ),
                fields=("tenant", "surface"),
                name="uniq_live_custom_host_surface",
            ),
        ),
    ]
