"""
Compiling PostBox rules into Sieve, and installing them over ManageSieve.

WHY COMPILE RATHER THAN ACCEPT SIEVE
    Sieve is a programming language that runs as the mail server, and it has
    `redirect` — which forwards a copy of somebody's mail anywhere. A browser
    that could post raw Sieve would be a browser that could exfiltrate a
    mailbox with one API call.

    So the browser posts a condition and an action from a fixed vocabulary,
    and this module renders the script. The generated text is the only Sieve
    that ever reaches Dovecot, every value in it is quoted by `_quote`, and
    the rule vocabulary contains no forwarding action at all.

WHY IT IS ONE SCRIPT
    Sieve evaluates a single active script top to bottom. Rules and the
    vacation responder therefore have to be rendered together, in order, with
    `stop` where the user asked for it — generating two scripts and hoping
    Dovecot merges them is not a thing Sieve does.

HOW IT IS INSTALLED
    ManageSieve (RFC 5804) on the engine network, authenticated with the same
    master identity PostBox reads mail with. Not by writing a file: Django has
    no access to the mail store's filesystem and should not have, and a script
    written directly would not be compiled or activated.
"""
from __future__ import annotations

import logging
import re
import socket
import ssl
from dataclasses import dataclass

from django.conf import settings

logger = logging.getLogger(__name__)

#: The script PostBox owns. A mailbox may in principle have others; PostBox
#: only ever writes and activates this one, so a script installed by some other
#: tool is left alone rather than silently replaced.
SCRIPT_NAME = "matemail-postbox"


class SieveError(Exception):
    def __init__(self, customer_message: str, log_message: str = ""):
        super().__init__(customer_message)
        self.customer_message = customer_message
        self.log_message = log_message or customer_message


@dataclass
class CompiledScript:
    body: str
    requires: list[str]


def _quote(value: str) -> str:
    """
    A Sieve quoted-string.

    Backslash first — reversing the order would escape the backslashes that
    the quote-escaping just added. Control characters are removed rather than
    escaped: a newline inside a string would end the statement, and no
    legitimate rule contains one.
    """
    cleaned = re.sub(r"[\x00-\x1f\x7f]", "", value or "")
    return '"' + cleaned.replace("\\", "\\\\").replace('"', '\\"') + '"'


#: Rule field → Sieve header. `to` covers Cc as well, because "sent to me"
#: is what a person means by it, and a rule that ignored Cc would quietly miss
#: half the mail it was written for.
_HEADERS = {
    "from": ["From"],
    "to": ["To", "Cc"],
    "subject": ["Subject"],
}

_MATCH = {
    "contains": ":contains",
    "is": ":is",
}


def compile_rules(rules, vacation=None, *, valid_folders: set[str] | None = None) -> CompiledScript:
    """
    Render the mailbox's rules, in order, plus the vacation responder.

    `valid_folders` is the mailbox's real folder list. A rule naming a folder
    that does not exist is mail going nowhere, so such a rule is skipped and
    logged rather than compiled — `fileinto` into a missing mailbox is a
    runtime error in Sieve, which would break every rule after it too.
    """
    requires: set[str] = set()
    lines: list[str] = [
        "# Generated by MateMail PostBox. Do not edit by hand:",
        "# this script is replaced whenever the mailbox's rules change.",
        "",
    ]

    for rule in rules:
        if not rule.enabled:
            continue

        headers = _HEADERS.get(rule.field)
        match = _MATCH.get(rule.match)
        if not headers or not match:
            logger.warning("PostBox: skipping rule %s with unknown field/match", rule.pk)
            continue

        if rule.action == "move":
            folder = (rule.action_folder or "").strip()
            if valid_folders is not None and folder not in valid_folders:
                logger.warning(
                    "PostBox: rule %s targets missing folder %r — skipped", rule.pk, folder
                )
                continue

        header_list = ", ".join(_quote(h) for h in headers)
        lines.append(f"# {rule.name}")
        lines.append(f"if header {match} [{header_list}] {_quote(rule.value)}")
        lines.append("{")

        if rule.action == "move":
            requires.add("fileinto")
            lines.append(f"    fileinto {_quote(rule.action_folder)};")
        elif rule.action == "star":
            requires.add("imap4flags")
            lines.append('    addflag "\\\\Flagged";')
        elif rule.action == "mark_read":
            requires.add("imap4flags")
            lines.append('    addflag "\\\\Seen";')
        elif rule.action == "delete":
            requires.add("fileinto")
            lines.append('    fileinto "Trash";')

        if rule.stop_processing:
            lines.append("    stop;")
        lines.append("}")
        lines.append("")

    if vacation is not None and vacation.is_active_now and vacation.message.strip():
        requires.add("vacation")
        days = max(1, min(int(vacation.repeat_days or 7), 60))
        lines.append("# Automatic reply")
        lines.append("vacation")
        lines.append(f"    :days {days}")
        if vacation.subject.strip():
            lines.append(f"    :subject {_quote(vacation.subject.strip())}")
        lines.append(f"    {_quote(vacation.message.strip())};")
        lines.append("")

    header = ""
    if requires:
        header = "require [" + ", ".join(_quote(r) for r in sorted(requires)) + "];\n\n"

    return CompiledScript(body=header + "\n".join(lines), requires=sorted(requires))


# ── ManageSieve ─────────────────────────────────────────────────────────────

class ManageSieveClient:
    """
    A minimal ManageSieve client: PUTSCRIPT, SETACTIVE, DELETESCRIPT.

    Deliberately small. The protocol is line-oriented with literals, and the
    three commands PostBox needs are simple; a general-purpose client would be
    more code to audit for something that writes executable rules to the mail
    server.
    """

    def __init__(self, sock: socket.socket):
        self._sock = sock
        self._buffer = b""

    # ── framing ─────────────────────────────────────────────────────────────

    def _read_line(self) -> bytes:
        while b"\r\n" not in self._buffer:
            chunk = self._sock.recv(8192)
            if not chunk:
                raise SieveError(
                    "Your filters could not be saved.", "ManageSieve closed the connection"
                )
            self._buffer += chunk
        line, _, self._buffer = self._buffer.partition(b"\r\n")
        return line

    def _read_response(self) -> tuple[str, str]:
        """Read until OK / NO / BYE. Returns (status, text)."""
        while True:
            line = self._read_line()
            upper = line.upper()
            if upper.startswith(b"OK"):
                return "OK", line.decode("utf-8", "replace")
            if upper.startswith(b"NO") or upper.startswith(b"BYE"):
                return "NO", line.decode("utf-8", "replace")
            # Capability lines and literals are not interesting to us.

    def _send(self, data: bytes) -> None:
        self._sock.sendall(data)

    # ── commands ────────────────────────────────────────────────────────────

    def authenticate(self, authorize_as: str, master_user: str, password: str) -> None:
        """
        SASL PLAIN, with the authorisation identity set to the mailbox.

        `authzid\\0authcid\\0password` — "act as this mailbox, authenticated as
        the PostBox service identity". The same master mechanism used for IMAP,
        so there is one privileged credential rather than two.
        """
        import base64

        payload = f"{authorize_as}\0{master_user}\0{password}".encode()
        encoded = base64.b64encode(payload).decode()
        self._send(f'AUTHENTICATE "PLAIN" "{encoded}"\r\n'.encode())
        status, text = self._read_response()
        if status != "OK":
            raise SieveError(
                "Your filters could not be saved.", f"ManageSieve AUTHENTICATE -> {text}"
            )

    def put_script(self, name: str, body: str) -> None:
        encoded = body.encode("utf-8")
        self._send(f'PUTSCRIPT "{name}" {{{len(encoded)}+}}\r\n'.encode())
        self._send(encoded + b"\r\n")
        status, text = self._read_response()
        if status != "OK":
            # A compile error lands here. The customer message stays generic —
            # Sieve diagnostics are about generated code they never wrote.
            raise SieveError(
                "Your filters could not be saved.", f"ManageSieve PUTSCRIPT -> {text}"
            )

    def set_active(self, name: str) -> None:
        self._send(f'SETACTIVE "{name}"\r\n'.encode())
        status, text = self._read_response()
        if status != "OK":
            raise SieveError(
                "Your filters were saved but could not be activated.",
                f"ManageSieve SETACTIVE -> {text}",
            )

    def logout(self) -> None:
        try:
            self._send(b"LOGOUT\r\n")
        except OSError:
            pass


def install_script(address: str, body: str) -> None:
    """
    Compile-and-activate this mailbox's script. Replaces any previous version.

    An empty script is still installed, and then deactivated: a mailbox whose
    last rule was deleted must stop filtering, and leaving the old script
    active would keep applying rules the person can no longer see.
    """
    host = getattr(settings, "POSTBOX_SIEVE_HOST", "")
    port = int(getattr(settings, "POSTBOX_SIEVE_PORT", 4190))
    master_user = getattr(settings, "POSTBOX_MASTER_USER", "postbox")
    master_password = getattr(settings, "POSTBOX_MASTER_PASSWORD", "")

    if not host or not master_password:
        raise SieveError(
            "Filters are not available. Please contact your administrator.",
            "POSTBOX_SIEVE_HOST or POSTBOX_MASTER_PASSWORD is unset",
        )

    try:
        sock = socket.create_connection((host, port), timeout=15)
    except OSError as exc:
        raise SieveError(
            "Filters are temporarily unavailable. Please try again shortly.",
            f"ManageSieve connect {host}:{port} failed: {exc!r}",
        ) from exc

    client = ManageSieveClient(sock)
    try:
        client._read_line()  # greeting and capabilities
        if getattr(settings, "POSTBOX_SIEVE_STARTTLS", False):
            client._send(b"STARTTLS\r\n")
            client._read_response()
            sock = ssl.create_default_context().wrap_socket(
                sock, server_hostname=host
            )
            client = ManageSieveClient(sock)
            client._read_line()

        client.authenticate(address, master_user, master_password)
        client.put_script(SCRIPT_NAME, body)

        if body.strip():
            client.set_active(SCRIPT_NAME)
        else:
            # Deactivate rather than delete, so the empty script is visible
            # evidence that PostBox owns this slot.
            client._send(b'SETACTIVE ""\r\n')
            client._read_response()
    finally:
        client.logout()
        try:
            sock.close()
        except OSError:
            pass


def sync_mailbox_rules(mailbox, *, valid_folders: set[str] | None = None) -> None:
    """
    Render and install everything for one mailbox.

    Called after any rule or vacation change. Failures propagate: a filter the
    person believes is active but which was never installed is worse than an
    error message.
    """
    from .models import MailRule, VacationResponder

    rules = list(MailRule.objects.for_mailbox(mailbox).order_by("position", "created_at"))
    vacation = VacationResponder.objects.filter(mailbox=mailbox).first()

    script = compile_rules(rules, vacation, valid_folders=valid_folders)
    install_script(mailbox.email, script.body)
    logger.info(
        "PostBox: installed %d rule(s) for mailbox %s (vacation=%s)",
        len(rules), mailbox.pk, bool(vacation and vacation.is_active_now),
    )
