# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('mailboxes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_address', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('destination_address', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('mail_engine_provisioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_aliases', to='mailboxes.mailbox')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='domains.domain')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='tenants.tenant')),
            ],
            options={
                'db_table': 'aliases_alias',
                'ordering': ['source_address'],
            },
        ),
    ]
