# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('warning', 'Warning'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('dns_health_score', models.IntegerField(default=0)),
                ('dkim_selector', models.CharField(default='mm1', max_length=63)),
                ('dkim_public_key', models.TextField(blank=True)),
                ('mail_engine_provisioned', models.BooleanField(default=False)),
                ('mail_engine_error', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'domains_domain',
                'ordering': ['-added_at'],
            },
        ),
    ]
