# Generated by Django 5.1.4 on 2026-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_dkim_private_key'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ownership_status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='ownership_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('tenant', 'domain'), name='uniq_domain_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('ownership_status', 'verified')), fields=('domain',), name='uniq_verified_domain_owner'),
        ),
    ]
