# Generated by Django 5.1.4 on 2026-09-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_encrypt_dkim_private_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ownership_recheck_failures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
