# Generated by Django 5.1.4 on 2026-09-20 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBoxPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=12)),
                ('reading_pane', models.CharField(choices=[('right', 'Right'), ('bottom', 'Bottom'), ('off', 'Off')], default='right', max_length=8)),
                ('load_remote_images', models.BooleanField(default=False)),
                ('messages_per_page', models.PositiveSmallIntegerField(default=50)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_sound', models.BooleanField(default=False)),
                ('default_identity', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_preference', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_preference',
            },
        ),
        migrations.CreateModel(
            name='VacationResponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_days', models.PositiveSmallIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_vacation', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_vacation',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_contacts', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_contact',
                'ordering': ['name', 'email'],
                'indexes': [models.Index(fields=['mailbox', 'email'], name='postbox_con_mailbox_bfd46f_idx'), models.Index(fields=['mailbox', 'name'], name='postbox_con_mailbox_49b013_idx')],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'email'), name='postbox_contact_unique_email')],
            },
        ),
        migrations.CreateModel(
            name='MailRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('field', models.CharField(choices=[('from', 'From'), ('to', 'To or Cc'), ('subject', 'Subject')], max_length=16)),
                ('match', models.CharField(choices=[('contains', 'contains'), ('is', 'is exactly')], default='contains', max_length=16)),
                ('value', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('move', 'Move to folder'), ('star', 'Star'), ('mark_read', 'Mark as read'), ('delete', 'Move to Trash')], max_length=16)),
                ('action_folder', models.CharField(blank=True, default='', max_length=200)),
                ('stop_processing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_rules', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_rule',
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['mailbox', 'position'], name='postbox_rul_mailbox_f4e6f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MailSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('html', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('use_for_new', models.BooleanField(default=False)),
                ('use_for_replies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_signatures', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_signature',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'name'), name='postbox_signature_unique_name')],
            },
        ),
        migrations.CreateModel(
            name='PostBoxSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('remembered', models.BooleanField(default=False)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_sessions', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_session',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['mailbox', '-last_seen_at'], name='postbox_ses_mailbox_0386ce_idx'), models.Index(fields=['expires_at'], name='postbox_ses_expires_94aca2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.CharField(default='Scheduled', max_length=200)),
                ('uid_validity', models.BigIntegerField()),
                ('uid', models.BigIntegerField()),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('recipients', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_message_id', models.CharField(blank=True, default='', max_length=998)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_scheduled', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_scheduled_message',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['state', 'scheduled_at'], name='postbox_sch_state_fc2fab_idx'), models.Index(fields=['mailbox', '-scheduled_at'], name='postbox_sch_mailbox_35c4f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'folder', 'uid_validity', 'uid'), name='postbox_scheduled_unique_message')],
            },
        ),
    ]
