# Generated by Django 5.1.4 on 2026-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0002_signature_default_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsignature',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='image_data',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='image_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailsignature',
            name='kind',
            field=models.CharField(choices=[('text', 'Plain text'), ('html', 'HTML'), ('image', 'Image')], default='text', max_length=8),
        ),
    ]
