# Generated by Django 5.1.4 on 2026-09-25 19:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
        ('postbox', '0004_signature_kind_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBoxPushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows')], max_length=10)),
                ('provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('wns', 'Windows Push Notification Services')], max_length=10)),
                ('token_type', models.CharField(choices=[('registration_token', 'FCM registration token'), ('fid', 'Firebase installation ID'), ('channel_uri', 'WNS channel URI')], max_length=20)),
                ('token', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=32)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=32)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_push_devices', to='mailboxes.mailbox')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='postbox.postboxsession')),
            ],
            options={
                'db_table': 'postbox_push_device',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['mailbox', 'enabled'], name='postbox_pus_mailbox_806880_idx')],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'installation_id', 'provider'), name='postbox_push_device_unique_installation')],
            },
        ),
        migrations.CreateModel(
            name='PostBoxPushEvent',
            fields=[
                ('event_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('new_mail', 'New mail')], default='new_mail', max_length=16)),
                ('folder', models.CharField(max_length=255)),
                ('uid_validity', models.BigIntegerField(blank=True, null=True)),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('devices', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbox_push_events', to='mailboxes.mailbox')),
            ],
            options={
                'db_table': 'postbox_push_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='postbox_pus_state_e1bff2_idx')],
            },
        ),
    ]
