# Generated by Django 5.2.14 on 2026-05-29 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('local_part', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('quota_mb', models.PositiveIntegerField(default=10240)),
                ('storage_used_mb', models.PositiveIntegerField(default=0)),
                ('mail_engine_provisioned', models.BooleanField(default=False)),
                ('mail_engine_error', models.TextField(blank=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='domains.domain')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'mailboxes_mailbox',
                'ordering': ['email'],
                'unique_together': {('tenant', 'local_part', 'domain')},
            },
        ),
    ]
